version: 2

models:
  - name: dim_users
    description: "Information about users and their associated orders"
    columns:
      - name: address_id
        description: "The primary key for this table"
        tests:  
          - unique
          - not_null
  - name: fct_sessions
    description: "Events rolled up to the grain of the session"
    columns:
      - name: session_id
        tests:
          - unique
      - name: session_length_minutes
        description: "The duration of the session"
        tests:
          - positive_values
  - name: fct_orders
    description: "Row for every order with some additional info about the entire order added"
    columns:
      - name: days_to_delivery
        description: "Days between created_date and delivered_date"
      - name: days_delivered_late
        description: "Days between delivered_date and estimated_delivery_date. If positive, the number of days delivered early."